# Python configuration for Pyrrha Platform
# Based on proven Pyrrha-Rules-Decision and Dashboard configurations
[tool.black]
line-length = 127
target-version = ['py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | lib
  | python3
)/
'''

[tool.isort]
profile = "black"
line_length = 127
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
install_types = true
non_interactive = true

[tool.flake8]
max-line-length = 127
max-complexity = 10
extend-ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "build", 
    "dist",
    "node_modules",
    "lib",
    "python3"
]
count = true
show-source = true
statistics = true