name: linter

on:
  # Execute on every push to any branch
  push:
    branches:
      - "**"
  # Execute on every pull request to the master branch
  pull_request_target:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y gcc libmariadb-dev libmariadb3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy bandit safety
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Format check with Black
        run: |
          black --check --diff .

      - name: Import sorting check with isort
        run: |
          isort --check-only --diff .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude lib,python3
          # exit-zero treats all errors as warnings. GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude lib,python3

      - name: Type checking with mypy
        run: |
          mypy --install-types --non-interactive . || true

      - name: Security check with bandit
        run: |
          bandit -r . -f json -o bandit-report.json || true

      - name: Dependency security check with safety
        run: |
          safety check --json --output safety-report.json || true

      - name: Set up node for Dockerfile linting
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install and run dockerfilelint
        run: |
          npm install -g dockerfilelint
          dockerfilelint Dockerfile*